apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nuhman9260/hosp-connect-api-gateway:latest
          ports:
            - containerPort: 8080
          env:
          - name: USER_GRPC_SERVER
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: USER_GRPC_SERVER
          - name: APPT_GRPC_SERVER
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: APPT_GRPC_SERVER
          - name: PAYMENT_GRPC_SERVER
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: PAYMENT_GRPC_SERVER
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: CLIENT_SECRET
          - name: MONITORING_ENABLED
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: MONITORING_ENABLED
          - name: IP_ADDRESS
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: IP_ADDRESS
          - name: DIALOG_FLOW_CREDENTIALS_JSON
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: DIALOG_FLOW_CREDENTIALS_JSON
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
