apiVersion: apps/v1
kind: Deployment
metadata:
  name: appt-svc-deployment
  labels:
    app: appt-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appt-svc
  template:
    metadata:
      labels:
        app: appt-svc
    spec:
      containers:
        - name: appt-svc
          image: nuhman9260/hosp-connect-appt-svc:latest
          ports:
            - containerPort: 50052
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: APPT_DATABASE_URL
          - name: APPT_PORT
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: APPT_PORT

          - name: USER_GRPC_SERVER
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: USER_GRPC_SERVER

          - name: PAYMENT_GRPC_SERVER
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: PAYMENT_GRPC_SERVER
          - name: IP_ADDRESS
            valueFrom:
              secretKeyRef:
                name: hosp-connect-secret
                key: IP_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: appt-svc-service
spec:
  selector:
    app: appt-svc
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
